# Axe-Edit III Accessibility - NVDA app module
# Copyright (C) 2026 Big Saurus
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2, as published by the
# Free Software Foundation. This program is distributed WITHOUT ANY WARRANTY.
# See the LICENSE file (GNU GPL v2) distributed with this add-on for details.

"""
appModules/fm9-edit.py

Binds the shared Fractal editor support to FM9-Edit (FM9 / FM9 Turbo).

UNTESTED. Fractal's editors share a JUCE codebase and the control-naming
patterns this add-on relies on are generated by that shared code, so the fixes
are expected to apply -- but nobody has confirmed it against an FM9 yet.

The module name must match the executable. ``FM9-Edit.exe`` is derived from
Fractal's macOS bundle name (``FM9-Edit.app``), which matches the Windows
executable name exactly for Axe-Edit III (``Axe-Edit III.app`` /
``Axe-Edit III.exe``). If NVDA reports nothing at all in FM9-Edit, the first
thing to check is the real process name in Task Manager's Details tab; if it
differs, renaming this file to match it is the entire fix.

Press NVDA+Shift+D with FM9-Edit focused to save a diagnostic dump to the
Desktop, which is enough to confirm or correct everything here.
"""

try:
    from .fractalEditCore import AppModule  # noqa: F401
except ImportError:  # pragma: no cover - defensive; package context varies
    from appModules.fractalEditCore import AppModule  # noqa: F401
